import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface ReportData {
    fileName: string;
    charCount: number;
    tokenCount: number;
    isExact: boolean;
}

interface OverallStats {
    totalTokens: number;
    totalChars: number;
}

export const generatePDFReport = (files: ReportData[], overallStats: OverallStats) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;

    // Header Background
    doc.setFillColor(30, 41, 59); // zinc-800 equivalent
    doc.rect(0, 0, pageWidth, 40, 'F');

    // Title
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.text("Tokenator Report", 14, 25);

    // Subtitle/Date
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(200, 200, 200);
    doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 34);

    // Stats Cards Section
    let yPos = 55;
    doc.setTextColor(30, 41, 59);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Analysis Summary", 14, yPos);

    yPos += 10;

    // Draw summary box
    doc.setDrawColor(226, 232, 240); // slate-200
    doc.setFillColor(248, 250, 252); // slate-50
    doc.roundedRect(14, yPos, pageWidth - 28, 35, 3, 3, 'FD');

    yPos += 12;
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");

    // Columns for stats
    const col1 = 20;
    const col2 = 80;
    const col3 = 140;

    doc.text("Total Files", col1, yPos);
    doc.text("Total Tokens", col2, yPos);
    doc.text("Total Characters", col3, yPos);

    yPos += 8;
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(37, 99, 235); // blue-600

    doc.text(files.length.toString(), col1, yPos);
    doc.text(overallStats.totalTokens.toLocaleString(), col2, yPos);
    doc.text(overallStats.totalChars.toLocaleString(), col3, yPos);

    // Usage Bar logic illustration in text
    yPos += 25;
    const percentage = (overallStats.totalTokens / 1000000) * 100;
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139); // slate-500
    doc.setFont("helvetica", "bold");
    doc.text(`Context Window Usage (${percentage.toFixed(2)}% of 1M limit)`, 14, yPos);

    // Table
    const tableData = files.map(file => [
        file.fileName,
        file.charCount.toLocaleString(),
        file.tokenCount.toLocaleString(),
        file.isExact ? "Verified (API)" : "Estimated"
    ]);

    autoTable(doc, {
        startY: yPos + 5,
        head: [["File Name", "Characters", "Tokens", "Method"]],
        body: tableData,
        theme: 'grid',
        styles: {
            font: "helvetica",
            fontSize: 10,
            cellPadding: 5,
        },
        headStyles: {
            fillColor: [30, 41, 59], // Dark header
            textColor: [255, 255, 255],
            fontStyle: 'bold'
        },
        alternateRowStyles: {
            fillColor: [241, 245, 249] // slate-100
        },
        columnStyles: {
            0: { cellWidth: 'auto' }, // File Name
            1: { halign: 'right' },   // Chars
            2: { halign: 'right', fontStyle: 'bold', textColor: [37, 99, 235] },   // Tokens
            3: { halign: 'center' }   // Method
        }
    });

    // Footer
    const pageCount = doc.internal.pages.length - 1; // jspdf starts with 1 page
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.text(`Page ${i} of ${pageCount}`, 196, 285, { align: "right" });
        doc.text("Generated by Tokenator", 14, 285);
    }

    doc.save("tokenator_report.pdf");
};
